### ISSUE TITLE
Log rejected promises

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-raven#26]
But only to splunk http://www.2ality.com/2016/04/unhandled-rejections.html

**Comment by matthew-andrews** [comment]
+1

**Comment by wheresrhys** [comment]
Need to reflect more on this as it will likely be very noisy because the following will also fire the event, so even when we handle errors they'll still be logged :-(
```
process.on('unhandledRejection', (reason) => {
    console.log('Reason: ' + reason);
});
function foo() {
    Promise.reject('abc').then(() => {});
}
foo();
```
