### ISSUE TITLE
Is it important to send a response on local development?

### ISSUE THREAD

**Issue by GlynnPhillips** [Financial-Times/n-raven#28]
When running an application locally errors are obviously not sent to raven and instead it sends a response with the status of `500` which is done [here](https://github.com/Financial-Times/n-raven/blob/master/main.js#L28)

This can cause errors on local environments which do not reflect production when an application also sends a response. 

As I have zero knowledge of this module I am wondering how important is it to send a response on local environments? or could we log something like "On production an error would have been sent to raven here" instead of sending a response?

**Comment by rowanmanning** [comment]
Hi Glynn. Assuming you don't care about this any more :D if you do then I think [Reliability Kit](https://github.com/Financial-Times/dotcom-reliability-kit/issues) might be the best place to reopen a new feature request
